module.exports = Object.freeze({
  sample_albums: {
    href:
      "https://api.spotify.com/v1/artists/3meJIgRw7YleJrmbpbJK6S/albums?offset=0&limit=20&include_groups=album,single,compilation,appears_on",
    items: [
      {
        album_group: "album",
        album_type: "album",
        artists: [Array],
        available_markets: [Array],
        external_urls: [Object],
        href: "https://api.spotify.com/v1/albums/76M62o1rdKEqTN1JIbGdGV",
        id: "76M62o1rdKEqTN1JIbGdGV",
        images: [Array],
        name: "und der dreiäugige Totenkopf",
        release_date: "2020-02-07",
        release_date_precision: "day",
        total_tracks: 61,
        type: "album",
        uri: "spotify:album:76M62o1rdKEqTN1JIbGdGV",
      },
      {
        album_group: "album",
        album_type: "album",
        artists: [Array],
        available_markets: [Array],
        external_urls: [Object],
        href: "https://api.spotify.com/v1/albums/79Drf49yNdGLBzzHMGGmBz",
        id: "79Drf49yNdGLBzzHMGGmBz",
        images: [Array],
        name: "203/Tauchgang ins Ungewisse",
        release_date: "2020-01-31",
        release_date_precision: "day",
        total_tracks: 42,
        type: "album",
        uri: "spotify:album:79Drf49yNdGLBzzHMGGmBz",
      },
      {
        album_group: "album",
        album_type: "album",
        artists: [Array],
        available_markets: [Array],
        external_urls: [Object],
        href: "https://api.spotify.com/v1/albums/553NN3wSa7Sb1o4hiYvuKf",
        id: "553NN3wSa7Sb1o4hiYvuKf",
        images: [Array],
        name: "Jessica Schwarz liest ...und der magische Kreis",
        release_date: "2020-01-17",
        release_date_precision: "day",
        total_tracks: 125,
        type: "album",
        uri: "spotify:album:553NN3wSa7Sb1o4hiYvuKf",
      },
      {
        album_group: "album",
        album_type: "album",
        artists: [Array],
        available_markets: [Array],
        external_urls: [Object],
        href: "https://api.spotify.com/v1/albums/3JipEukbhM5xpewSjT2KPX",
        id: "3JipEukbhM5xpewSjT2KPX",
        images: [Array],
        name: "Bela B liest... und der tanzende Teufel",
        release_date: "2019-12-13",
        release_date_precision: "day",
        total_tracks: 128,
        type: "album",
        uri: "spotify:album:3JipEukbhM5xpewSjT2KPX",
      },
      {
        album_group: "album",
        album_type: "album",
        artists: [Array],
        available_markets: [Array],
        external_urls: [Object],
        href: "https://api.spotify.com/v1/albums/4Exxckn0GwbhnGl6N4um2N",
        id: "4Exxckn0GwbhnGl6N4um2N",
        images: [Array],
        name: "202/Das weiße Grab",
        release_date: "2019-11-29",
        release_date_precision: "day",
        total_tracks: 42,
        type: "album",
        uri: "spotify:album:4Exxckn0GwbhnGl6N4um2N",
      },
      {
        album_group: "album",
        album_type: "album",
        artists: [Array],
        available_markets: [Array],
        external_urls: [Object],
        href: "https://api.spotify.com/v1/albums/4ylLMiYlbxfICFmZ9Va8P0",
        id: "4ylLMiYlbxfICFmZ9Va8P0",
        images: [Array],
        name: "Andreas Fröhlich liest...und der Karpatenhund",
        release_date: "2019-11-22",
        release_date_precision: "day",
        total_tracks: 125,
        type: "album",
        uri: "spotify:album:4ylLMiYlbxfICFmZ9Va8P0",
      },
      {
        album_group: "album",
        album_type: "album",
        artists: [Array],
        available_markets: [Array],
        external_urls: [Object],
        href: "https://api.spotify.com/v1/albums/0msYXbGb3x5Ye5ulasSxL2",
        id: "0msYXbGb3x5Ye5ulasSxL2",
        images: [Array],
        name: "Jens Wawrczeck liest ...und das Gespensterschloß",
        release_date: "2019-11-22",
        release_date_precision: "day",
        total_tracks: 125,
        type: "album",
        uri: "spotify:album:0msYXbGb3x5Ye5ulasSxL2",
      },
      {
        album_group: "album",
        album_type: "album",
        artists: [Array],
        available_markets: [Array],
        external_urls: [Object],
        href: "https://api.spotify.com/v1/albums/5JZMdAzeapgfnOqGVs9Xai",
        id: "5JZMdAzeapgfnOqGVs9Xai",
        images: [Array],
        name: "Oliver Rohrbeck liest ...und der Super-Papagei",
        release_date: "2019-11-22",
        release_date_precision: "day",
        total_tracks: 131,
        type: "album",
        uri: "spotify:album:5JZMdAzeapgfnOqGVs9Xai",
      },
      {
        album_group: "album",
        album_type: "album",
        artists: [Array],
        available_markets: [Array],
        external_urls: [Object],
        href: "https://api.spotify.com/v1/albums/48MEVXeUF6qgWOSDVzDMCl",
        id: "48MEVXeUF6qgWOSDVzDMCl",
        images: [Array],
        name: "Jannik Schümann liest ...und der Phantomsee",
        release_date: "2019-11-08",
        release_date_precision: "day",
        total_tracks: 105,
        type: "album",
        uri: "spotify:album:48MEVXeUF6qgWOSDVzDMCl",
      },
      {
        album_group: "album",
        album_type: "album",
        artists: [Array],
        available_markets: [Array],
        external_urls: [Object],
        href: "https://api.spotify.com/v1/albums/6UN8m07SmIzyDe63H0oljL",
        id: "6UN8m07SmIzyDe63H0oljL",
        images: [Array],
        name: "und das versunkene Schiff",
        release_date: "2019-11-01",
        release_date_precision: "day",
        total_tracks: 82,
        type: "album",
        uri: "spotify:album:6UN8m07SmIzyDe63H0oljL",
      },
      {
        album_group: "album",
        album_type: "album",
        artists: [Array],
        available_markets: [Array],
        external_urls: [Object],
        href: "https://api.spotify.com/v1/albums/6RRNvBOpoTTfS0CmVVnKiQ",
        id: "6RRNvBOpoTTfS0CmVVnKiQ",
        images: [Array],
        name: "Anna Thalbach liest... und die Geisterinsel (ungekürzte Lesung)",
        release_date: "2019-10-18",
        release_date_precision: "day",
        total_tracks: 99,
        type: "album",
        uri: "spotify:album:6RRNvBOpoTTfS0CmVVnKiQ",
      },
      {
        album_group: "album",
        album_type: "album",
        artists: [Array],
        available_markets: [Array],
        external_urls: [Object],
        href: "https://api.spotify.com/v1/albums/4FxNfDSXqAg8N1D8NBtvZ5",
        id: "4FxNfDSXqAg8N1D8NBtvZ5",
        images: [Array],
        name: "201/Höhenangst",
        release_date: "2019-09-27",
        release_date_precision: "day",
        total_tracks: 42,
        type: "album",
        uri: "spotify:album:4FxNfDSXqAg8N1D8NBtvZ5",
      },
      {
        album_group: "album",
        album_type: "album",
        artists: [Array],
        available_markets: [Array],
        external_urls: [Object],
        href: "https://api.spotify.com/v1/albums/3EjzXEcI1CCOFYdrMcyHFh",
        id: "3EjzXEcI1CCOFYdrMcyHFh",
        images: [Array],
        name:
          "Bastian Pastewka liest... und der grüne Geist (Ungekürzte Lesung)",
        release_date: "2019-09-06",
        release_date_precision: "day",
        total_tracks: 101,
        type: "album",
        uri: "spotify:album:3EjzXEcI1CCOFYdrMcyHFh",
      },
      {
        album_group: "album",
        album_type: "album",
        artists: [Array],
        available_markets: [Array],
        external_urls: [Object],
        href: "https://api.spotify.com/v1/albums/09Ckx1JLgPsQHHGuSIt2j3",
        id: "09Ckx1JLgPsQHHGuSIt2j3",
        images: [Array],
        name: "200/Feuriges Auge",
        release_date: "2019-07-19",
        release_date_precision: "day",
        total_tracks: 162,
        type: "album",
        uri: "spotify:album:09Ckx1JLgPsQHHGuSIt2j3",
      },
      {
        album_group: "album",
        album_type: "album",
        artists: [Array],
        available_markets: [Array],
        external_urls: [Object],
        href: "https://api.spotify.com/v1/albums/7bTKP2hU0LRks1bXN1R7ko",
        id: "7bTKP2hU0LRks1bXN1R7ko",
        images: [Array],
        name: "199/und der grüne Kobold",
        release_date: "2019-06-28",
        release_date_precision: "day",
        total_tracks: 42,
        type: "album",
        uri: "spotify:album:7bTKP2hU0LRks1bXN1R7ko",
      },
      {
        album_group: "album",
        album_type: "album",
        artists: [Array],
        available_markets: [Array],
        external_urls: [Object],
        href: "https://api.spotify.com/v1/albums/4piiNuehCc4VjN8NBIcnRt",
        id: "4piiNuehCc4VjN8NBIcnRt",
        images: [Array],
        name: "198/Die Legende der Gaukler",
        release_date: "2019-03-08",
        release_date_precision: "day",
        total_tracks: 40,
        type: "album",
        uri: "spotify:album:4piiNuehCc4VjN8NBIcnRt",
      },
      {
        album_group: "album",
        album_type: "album",
        artists: [Array],
        available_markets: [Array],
        external_urls: [Object],
        href: "https://api.spotify.com/v1/albums/39K0Sczt1mIbW33lB5RNer",
        id: "39K0Sczt1mIbW33lB5RNer",
        images: [Array],
        name: "Und die schwarze Katze",
        release_date: "2019-02-15",
        release_date_precision: "day",
        total_tracks: 60,
        type: "album",
        uri: "spotify:album:39K0Sczt1mIbW33lB5RNer",
      },
      {
        album_group: "album",
        album_type: "album",
        artists: [Array],
        available_markets: [Array],
        external_urls: [Object],
        href: "https://api.spotify.com/v1/albums/0GRoTtX1wI16M7GSnnN96R",
        id: "0GRoTtX1wI16M7GSnnN96R",
        images: [Array],
        name: "197/Im Auge des Sturms",
        release_date: "2019-01-18",
        release_date_precision: "day",
        total_tracks: 40,
        type: "album",
        uri: "spotify:album:0GRoTtX1wI16M7GSnnN96R",
      },
      {
        album_group: "album",
        album_type: "album",
        artists: [Array],
        available_markets: [Array],
        external_urls: [Object],
        href: "https://api.spotify.com/v1/albums/39a7bHWZyWPxwukCHPrTly",
        id: "39a7bHWZyWPxwukCHPrTly",
        images: [Array],
        name: "196/Geheimnis des Bauchredners",
        release_date: "2018-11-30",
        release_date_precision: "day",
        total_tracks: 40,
        type: "album",
        uri: "spotify:album:39a7bHWZyWPxwukCHPrTly",
      },
      {
        album_group: "album",
        album_type: "album",
        artists: [Array],
        available_markets: [Array],
        external_urls: [Object],
        href: "https://api.spotify.com/v1/albums/7ehMwTyKuIM4zdiltMxE4X",
        id: "7ehMwTyKuIM4zdiltMxE4X",
        images: [Array],
        name: "und der schwarze Tag (Sechs Kurzgeschichten)",
        release_date: "2018-10-26",
        release_date_precision: "day",
        total_tracks: 120,
        type: "album",
        uri: "spotify:album:7ehMwTyKuIM4zdiltMxE4X",
      },
    ],
    limit: 20,
    next:
      "https://api.spotify.com/v1/artists/3meJIgRw7YleJrmbpbJK6S/albums?offset=20&limit=20&include_groups=album,single,compilation,appears_on",
    offset: 0,
    previous: null,
    total: 230,
  },
});
